### PR TITLE
Experiment adding CMake build system

### PR DESCRIPTION
**Pull request by saxbophone**
Greetings,

I had a go at creating a CMake build config for this project, using the existing autotools-based config as a guide; these are my results.

- I intended to get the project building in this way on Linux, macOS and Windows. As it turned out, I did not manage to get Windows builds working (as I learned how UNIX-centric this project is).
- **I have left the existing autotools build system mostly untouched, save for deleting the auto-generated `src/config.h` file (my CMake builds would not work with this file left in-situ, it was masking the `config.h` file that the CMake build system generates). I tried to verify that this file could still be regenerated with the autotools stuff, but I've not been able to verify that on my end, so I wanted to flag this to you because I'd rather not break your autotools builds unexpectedly like that.**
- The new `config.cmake.h.in` file I've created is based off the autotools version, except using CMake's equivalent configure-header syntax and I've also removed all macros I could find that aren't actually being used in the project at all.
- I created a config file that uses Github Actions to automatically build and "test" commits to the main branch. The current "testing" is very rudimentary (it just sees if it can run `stoical -h` and also execute the two demo programs, although they don't crash they don't seem to be actually executing successfully).

In any case, I'm conscious I've clobbered over the code a little bit here and not expecting a merge, but I'm sharing my experiment with you in case you might find it useful. I certainly found it useful myself as I've not been able to get the autotools build to work on my mac, but the CMake build does work (as long as you use GCC and not Clang!).

### CODE REVIEW

**Comment by mikewarot** [comment]
wow, you did a lot of work on this.

I've been spinning my wheels pretty hard too.

Someone else got it working (with a lot of warnings, of course) on Ubuntu 20... and I was able to clone it and run it there as well

https://github.com/fhars/stoical

I'm not sure what to do now..

Suggestions welcome

**Comment by saxbophone** [comment]
@mikewarot ooh, I didn't see that someone else had forked it and made more progress, thanks for mentioning that!
Maybe I will see what happens if I try integrating their work with what I've been working on... I was mostly curious on seeing if I could de-autotoolsify the project, beyond that I'm a little at a loss in terms of debugging it...

When you say that they got the project working, do you mean it's running better than this copy? I found that although I could get it to compile and execute without crashing (mostly!), getting it to actually do anything did not seem to be successful (mostly just a bunch of `undefined` return values in the REPL).

**Comment by mikewarot** [comment]
I'm fairly certain closing this pull request is the way to handle this, right?  Sorry if I'm doing something wrong, I'm new to this, as you know.

**Comment by saxbophone** [comment]
> I'm fairly certain closing this pull request is the way to handle this, right? Sorry if I'm doing something wrong, I'm new to this, as you know.

No problem @mikewarot —on Github, the convention is to close a pull request if the code offered in it is not going to be merged into your repo, or merge the pull request if it is going to be.

As it stands, I wasn't expecting my code to be merged without changes as I've removed something that allows the autotools-based build system (which everyone else except me seem to be using for this project!) to keep working, so merging it in its current state would likely cause you problems...

**Pull request closed without merging**
